import type { Metadata } from "next";
import {Inter, Spectral} from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const spectral = Spectral({
  weight: ["400", "500", "600", "700"],
  variable: "--font-spectral"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${spectral.variable} font-sans antialiased tracking-tight leading-tight`}>
        {children}
      </body>
    </html>
  );
}
